import { createContext, createElement, useContext, useState } from "react";

export const LANGUAGES = {
  en: {
    code: "en", label: "English", flag: "🇺🇸",
    t: {
      myRecipes: "My Recipes",
      recipes: "Recipes",
      mealPlan: "Meal Plan",
      community: "Chef Hub",
      settings: "Settings",
      addRecipe: "Add Recipe",
      addYourFirstRecipe: "Add Your First Recipe",
      noRecipesYet: "No recipes yet",
      noRecipesFound: "No recipes found",
      startBuilding: "Start building your recipe collection by adding your first recipe.",
      tryAdjusting: "Try adjusting your search or filters.",
      recipeInCollection: (n) => `${n} recipe${n !== 1 ? "s" : ""} in your collection`,
      searchPlaceholder: "Search recipes…",
      all: "All",
      breakfast: "Breakfast", lunch: "Lunch", dinner: "Dinner",
      snack: "Snack", dessert: "Dessert", drink: "Drink",
      ingredients: "Ingredients", instructions: "Instructions",
      servings: "servings", minTotal: "min total", prep: "prep", cook: "cook",
      edit: "Edit", delete: "Delete", back: "Back",
      deleteRecipe: "Delete Recipe",
      deleteConfirm: (name) => `Are you sure you want to delete "${name}"? This cannot be undone.`,
      cancel: "Cancel",
      account: "Account", logout: "Log out",
      dangerZone: "Danger Zone", deleteAccount: "Delete Account",
      deleteAccountWarning: "This will permanently delete your account and all associated data. This action cannot be undone.",
      deleting: "Deleting...",
      manageAccount: "Manage your account and preferences",
      newRecipe: "New Recipe", editRecipe: "Edit Recipe",
      generateWithAI: "Generate with AI",
      exportPDF: "Export PDF",
      language: "Language",
      recipeName: "Recipe Name", description: "Description", category: "Category",
      photo: "Photo", upload: "Upload", orPasteUrl: "Or paste image URL",
      prepTime: "Prep Time (min)", cookTime: "Cook Time (min)",
      tags: "Tags", steps: "Steps", addIngredient: "Add Ingredient",
      addStep: "Add Step", save: "Save", saving: "Saving...",
      createRecipe: "Create Recipe", updateRecipe: "Update Recipe",
      addMeal: "Add", chooseRecipe: "Choose a Recipe", searchRecipes: "Search recipes...",
      noRecipesFoundPicker: "No recipes found",
      planYourMeals: "Plan your meals for the week ahead",
      today: "Today",
      recipeNotFound: "Recipe not found.",
      share: "Share",
      sharedToCommunity: "Shared to community wall",
      groceryList: "Grocery List",
      servingsLabel: "Servings",
      qtyAmount: "Qty / Amount",
      amountLabel: "Amount",
      ingredientLabel: "Ingredient",
      generatedFromSavora: "Generated from Savora",
      groceryListFilePrefix: "Grocery_List",
      itemsChecked: "items checked",
      pdf: "PDF",
      allItemsCollected: "All items collected!",
      resetAll: "Reset All",
      communitySubtitle: "Share recipes, thoughts, and connect with others",
      noPostsYet: "No posts yet",
      beFirstToShare: "Be the first to share a recipe or start a conversation.",
      likes: "Likes",
      liked: "Liked",
      comment: "Comment",
      hideComments: "Hide comments",
      shareSomethingPlaceholder: "Share something with the community...",
      attachRecipe: "Attach Recipe",
      post: "Post",
    }
  },
  ko: {
    code: "ko", label: "한국어", flag: "🇰🇷",
    t: {
      myRecipes: "내 레시피",
      recipes: "레시피",
      community: "셰프허브",
      mealPlan: "식단 계획",
      settings: "설정",
      addRecipe: "레시피 추가",
      addYourFirstRecipe: "첫 레시피 추가하기",
      noRecipesYet: "아직 레시피가 없습니다",
      noRecipesFound: "레시피를 찾을 수 없습니다",
      startBuilding: "첫 번째 레시피를 추가하여 컬렉션을 시작하세요.",
      tryAdjusting: "검색어나 필터를 조정해 보세요.",
      recipeInCollection: (n) => `컬렉션에 레시피 ${n}개`,
      searchPlaceholder: "레시피 검색…",
      all: "전체",
      breakfast: "아침", lunch: "점심", dinner: "저녁",
      snack: "간식", dessert: "디저트", drink: "음료",
      ingredients: "재료", instructions: "조리 방법",
      servings: "인분", minTotal: "분 합계", prep: "준비", cook: "조리",
      edit: "편집", delete: "삭제", back: "뒤로",
      deleteRecipe: "레시피 삭제",
      deleteConfirm: (name) => `"${name}"을(를) 삭제하시겠습니까? 되돌릴 수 없습니다.`,
      cancel: "취소",
      account: "계정", logout: "로그아웃",
      dangerZone: "위험 구역", deleteAccount: "계정 삭제",
      deleteAccountWarning: "계정과 모든 관련 데이터가 영구적으로 삭제됩니다. 되돌릴 수 없습니다.",
      deleting: "삭제 중...",
      manageAccount: "계정 및 기본 설정 관리",
      newRecipe: "새 레시피", editRecipe: "레시피 편집",
      generateWithAI: "AI로 생성",
      exportPDF: "PDF 내보내기",
      language: "언어",
      recipeName: "레시피 이름", description: "설명", category: "카테고리",
      photo: "사진", upload: "업로드", orPasteUrl: "이미지 URL 붙여넣기",
      prepTime: "준비 시간 (분)", cookTime: "조리 시간 (분)",
      tags: "태그", steps: "단계", addIngredient: "재료 추가",
      addStep: "단계 추가", save: "저장", saving: "저장 중...",
      createRecipe: "레시피 만들기", updateRecipe: "레시피 업데이트",
      addMeal: "추가", chooseRecipe: "레시피 선택", searchRecipes: "레시피 검색...",
      noRecipesFoundPicker: "레시피를 찾을 수 없습니다",
      planYourMeals: "이번 주 식단을 계획하세요",
      today: "오늘",
      recipeNotFound: "레시피를 찾을 수 없습니다.",
      share: "공유",
      sharedToCommunity: "커뮤니티에 공유되었습니다",
      groceryList: "장보기 목록",
      servingsLabel: "인분",
      qtyAmount: "수량 / 분량",
      amountLabel: "분량",
      ingredientLabel: "재료",
      generatedFromSavora: "Savora에서 생성됨",
      groceryListFilePrefix: "장보기_목록",
      itemsChecked: "항목 체크됨",
      pdf: "PDF",
      allItemsCollected: "모든 항목을 준비했습니다!",
      resetAll: "모두 초기화",
      communitySubtitle: "레시피와 생각을 공유하고 다른 사람들과 소통하세요",
      noPostsYet: "아직 게시물이 없습니다",
      beFirstToShare: "첫 번째로 레시피를 공유하거나 대화를 시작해 보세요.",
      likes: "좋아요",
      liked: "좋아요함",
      comment: "댓글",
      hideComments: "댓글 숨기기",
      shareSomethingPlaceholder: "커뮤니티에 공유할 내용을 작성하세요...",
      attachRecipe: "레시피 첨부",
      post: "게시",
    }
  },
  ja: {
    code: "ja", label: "日本語", flag: "🇯🇵",
    t: {
      myRecipes: "マイレシピ",
      recipes: "レシピ",
      community: "シェフハブ",
      mealPlan: "食事計画",
      settings: "設定",
      addRecipe: "レシピを追加",
      addYourFirstRecipe: "最初のレシピを追加",
      noRecipesYet: "レシピがまだありません",
      noRecipesFound: "レシピが見つかりません",
      startBuilding: "最初のレシピを追加してコレクションを始めましょう。",
      tryAdjusting: "検索やフィルターを調整してみてください。",
      recipeInCollection: (n) => `コレクションに${n}件のレシピ`,
      searchPlaceholder: "レシピを検索…",
      all: "すべて",
      breakfast: "朝食", lunch: "昼食", dinner: "夕食",
      snack: "スナック", dessert: "デザート", drink: "ドリンク",
      ingredients: "材料", instructions: "作り方",
      servings: "人分", minTotal: "分合計", prep: "準備", cook: "調理",
      edit: "編集", delete: "削除", back: "戻る",
      deleteRecipe: "レシピを削除",
      deleteConfirm: (name) => `「${name}」を削除しますか？この操作は元に戻せません。`,
      cancel: "キャンセル",
      account: "アカウント", logout: "ログアウト",
      dangerZone: "危険ゾーン", deleteAccount: "アカウント削除",
      deleteAccountWarning: "アカウントとすべての関連データが完全に削除されます。この操作は元に戻せません。",
      deleting: "削除中...",
      manageAccount: "アカウントと設定を管理する",
      newRecipe: "新しいレシピ", editRecipe: "レシピを編集",
      generateWithAI: "AIで生成",
      exportPDF: "PDF出力",
      language: "言語",
      recipeName: "レシピ名", description: "説明", category: "カテゴリー",
      photo: "写真", upload: "アップロード", orPasteUrl: "画像URLを貼り付け",
      prepTime: "準備時間 (分)", cookTime: "調理時間 (分)",
      tags: "タグ", steps: "手順", addIngredient: "材料を追加",
      addStep: "手順を追加", save: "保存", saving: "保存中...",
      createRecipe: "レシピ作成", updateRecipe: "レシピ更新",
      addMeal: "追加", chooseRecipe: "レシピを選択", searchRecipes: "レシピを検索...",
      noRecipesFoundPicker: "レシピが見つかりません",
      planYourMeals: "今週の食事を計画しましょう",
      today: "今日",
      recipeNotFound: "レシピが見つかりません。",
      share: "共有",
      sharedToCommunity: "コミュニティに共有しました",
      groceryList: "買い物リスト",
      servingsLabel: "人数",
      qtyAmount: "数量 / 分量",
      amountLabel: "分量",
      ingredientLabel: "材料",
      generatedFromSavora: "Savora から生成",
      groceryListFilePrefix: "買い物リスト",
      itemsChecked: "項目チェック済み",
      pdf: "PDF",
      allItemsCollected: "すべての項目をチェックしました！",
      resetAll: "すべてリセット",
      communitySubtitle: "レシピやアイデアを共有し、みんなとつながりましょう",
      noPostsYet: "まだ投稿がありません",
      beFirstToShare: "最初にレシピを共有するか、会話を始めてみましょう。",
      likes: "いいね",
      liked: "いいね済み",
      comment: "コメント",
      hideComments: "コメントを隠す",
      shareSomethingPlaceholder: "コミュニティに共有したい内容を書いてください...",
      attachRecipe: "レシピを添付",
      post: "投稿",
    }
  },
  vi: {
    code: "vi", label: "Tiếng Việt", flag: "🇻🇳",
    t: {
      myRecipes: "Công Thức Của Tôi",
      recipes: "Công Thức",
      community: "Chef Hub",
      mealPlan: "Kế Hoạch Ăn",
      settings: "Cài Đặt",
      addRecipe: "Thêm Công Thức",
      addYourFirstRecipe: "Thêm Công Thức Đầu Tiên",
      noRecipesYet: "Chưa có công thức nào",
      noRecipesFound: "Không tìm thấy công thức",
      startBuilding: "Bắt đầu bộ sưu tập bằng cách thêm công thức đầu tiên.",
      tryAdjusting: "Hãy thử điều chỉnh tìm kiếm hoặc bộ lọc.",
      recipeInCollection: (n) => `${n} công thức trong bộ sưu tập`,
      searchPlaceholder: "Tìm kiếm công thức…",
      all: "Tất cả",
      breakfast: "Sáng", lunch: "Trưa", dinner: "Tối",
      snack: "Ăn vặt", dessert: "Tráng miệng", drink: "Đồ uống",
      ingredients: "Nguyên Liệu", instructions: "Hướng Dẫn",
      servings: "khẩu phần", minTotal: "phút tổng", prep: "chuẩn bị", cook: "nấu",
      edit: "Sửa", delete: "Xóa", back: "Quay lại",
      deleteRecipe: "Xóa Công Thức",
      deleteConfirm: (name) => `Bạn có chắc muốn xóa "${name}"? Không thể hoàn tác.`,
      cancel: "Hủy",
      account: "Tài Khoản", logout: "Đăng xuất",
      dangerZone: "Vùng Nguy Hiểm", deleteAccount: "Xóa Tài Khoản",
      deleteAccountWarning: "Điều này sẽ xóa vĩnh viễn tài khoản và tất cả dữ liệu liên quan. Không thể hoàn tác.",
      deleting: "Đang xóa...",
      manageAccount: "Quản lý tài khoản và tùy chọn",
      newRecipe: "Công Thức Mới", editRecipe: "Sửa Công Thức",
      generateWithAI: "Tạo bằng AI",
      exportPDF: "Xuất PDF",
      language: "Ngôn ngữ",
      recipeName: "Tên Công Thức", description: "Mô tả", category: "Danh mục",
      photo: "Ảnh", upload: "Tải lên", orPasteUrl: "Hoặc dán URL ảnh",
      prepTime: "Thời gian chuẩn bị (phút)", cookTime: "Thời gian nấu (phút)",
      tags: "Thẻ", steps: "Các bước", addIngredient: "Thêm nguyên liệu",
      addStep: "Thêm bước", save: "Lưu", saving: "Đang lưu...",
      createRecipe: "Tạo Công Thức", updateRecipe: "Cập Nhật Công Thức",
      addMeal: "Thêm", chooseRecipe: "Chọn Công Thức", searchRecipes: "Tìm công thức...",
      noRecipesFoundPicker: "Không tìm thấy công thức",
      planYourMeals: "Lên kế hoạch bữa ăn cho tuần tới",
      today: "Hôm nay",
      recipeNotFound: "Không tìm thấy công thức.",
      share: "Chia sẻ",
      sharedToCommunity: "Đã chia sẻ lên cộng đồng",
      groceryList: "Danh Sách Mua Sắm",
      servingsLabel: "Khẩu phần",
      qtyAmount: "Số lượng / Định lượng",
      amountLabel: "Định lượng",
      ingredientLabel: "Nguyên liệu",
      generatedFromSavora: "Được tạo từ Savora",
      groceryListFilePrefix: "Danh_Sach_Mua_Sam",
      itemsChecked: "mục đã chọn",
      pdf: "PDF",
      allItemsCollected: "Đã thu thập đủ tất cả mục!",
      resetAll: "Đặt lại tất cả",
      communitySubtitle: "Chia sẻ công thức, ý tưởng và kết nối với mọi người",
      noPostsYet: "Chưa có bài đăng nào",
      beFirstToShare: "Hãy là người đầu tiên chia sẻ công thức hoặc bắt đầu cuộc trò chuyện.",
      likes: "Lượt thích",
      liked: "Đã thích",
      comment: "Bình luận",
      hideComments: "Ẩn bình luận",
      shareSomethingPlaceholder: "Chia sẻ điều gì đó với cộng đồng...",
      attachRecipe: "Đính kèm công thức",
      post: "Đăng",
    }
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("savora_lang") || "en");
  const switchLang = (code) => {
    setLang(code);
    localStorage.setItem("savora_lang", code);
  };
  return createElement(
    LanguageContext.Provider,
    { value: { lang, switchLang, t: LANGUAGES[lang].t, LANGUAGES } },
    children,
  );
}

export function useLang() {
  return useContext(LanguageContext);
}